=== KarimBlackStar/3-TRIM_DAW/LM/XML/DTD/DTD9.dtd
<!ELEMENT pedido (tractor+)>

<!ELEMENT tractor (componente+)>

<!ELEMENT componente (fechaentrega?, fragil, peso, numserie, kmmaximos?)>
<!ATTLIST componente fabricante CDATA #REQUIRED>

<!ELEMENT fechaentrega (dia?, mes, anio)>
<!ELEMENT fragil (#PCDATA)>

<!ELEMENT peso (#PCDATA)>
<!ATTLIST peso unidad (kg|g) #REQUIRED>

<!ELEMENT numserie (#PCDATA)>
<!ELEMENT kmmaximos (#PCDATA)>

<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== KarimBlackStar/3-TRIM_DAW/LM/XML/ActividadesDTD9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedido SYSTEM "DTD/DTD9.dtd">
<pedido>
    <tractor>
        <componente nombrefabricante="Ebro">
            <fechaentrega>
                <mes>2018</mes>
                <anio>2018</anio>
            </fechaentrega>
            <fragil />
            <peso unidad="kg">12</peso>
            <numserie>00A</numserie>
        </componente>
        <componente nombrefabricante="Avia">
            <fechaentrega>
                <dia>12</dia>
                <mes>1</mes>
                <anio>2019</anio>
            </fechaentrega>
            <nofragil />
            <peso unidad="g">1450</peso>
            <numserie>00D</numserie>
            <kmmaximos>25000</kmmaximos>
        </componente>
    </tractor>
    <tractor>
        <componente nombrefabricante="John Deere">
            <fragil />
            <peso unidad="g">770</peso>
            <numserie>43Z</numserie>
        </componente>
    </tractor>
</pedido>
