=== KarimBlackStar/3-TRIM_DAW/LM/XML/DTD/menu.dtd
<!ELEMENT menu (entrantes, primeros, segundos, postres, bebidas)>

<!ELEMENT entrantes (entrante*,bebida+)>
<!ATTLIST bebida alcohol (si|no) #REQUIRED>
<!ELEMENT alcohol (#PCDATA)>
<!ELEMENT entrante (#PCDATA)>

<!ELEMENT primeros (primero+, sorbete?)>
<!ELEMENT primero (#PCDATA)>
<!ELEMENT sorbete (#PCDATA)>
<!ATTLIST sorbete alcohol (si|no) #REQUIRED>

<!ELEMENT segundos (segundo)>
<!ATTLIST segundos tipo (carne|perscado|vegetal) #REQUIRED>
<!ELEMENT segundo (#PCDATA)>

<!ELEMENT postres ((helado | macedonia), tarta)>
<!ATTLIST helado sabor CDATA #REQUIRED>
<!ELEMENT helado (#PCDATA)>
<!ELEMENT tarta (#PCDATA)>

<!ELEMENT bebidas (bebida, cafe?)*>
<!ATTLIST bebida alcohol (si|no) #REQUIRED>
<!ELEMENT cafe (#PCDATA)>
<!ELEMENT bebida (#PCDATA)>

=== KarimBlackStar/3-TRIM_DAW/LM/XML/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "DTD/menu.dtd">
<menu>

    <entrantes>

        <entrante>Jamón ibérico</entrante>
        <entrante>Queso manchego</entrante>

        <bebida alcohol="si">Vino blanco</bebida>

    </entrantes>

    <primeros>

        <primero>Ensalada de langostinos</primero>
        <primero>Crema de calabaza</primero>

        <sorbete alcohol="no">Sorbete de limón</sorbete>

    </primeros>

    <segundos tipo="carne">
       <segundo>Solomillo al horno</segundo> 
    </segundos>

    <postres>

        <helado sabor="vainilla">Helado artesanal</helado>
        <tarta>Tarta nupcial</tarta>

    </postres>

    <bebidas>

        <bebida alcohol="no">Agua mineral</bebida>
        <bebida alcohol="si">Cerveza</bebida>

        <cafe>Espresso</cafe>

    </bebidas>

</menu>
